# Generated by Django 5.1.3 on 2024-12-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
