# Generated by Django 5.1.3 on 2024-11-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatsession_chatmessage_delete_chathistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
